feat(RayTracing): add helpers to check a point is inside a closed sur…
Geode-solutions/OpenGeode pull request #1010
Opened 2024-09-02 11:52 UTC by BenPinet

…face

2024-09-02 11:58 UTC, panquez commented on src/geode/model/helpers/ray_tracing.cpp
> +            geode::Vector3D{ { 0., 0.5, 1. } } } };
Avoid duplication of these Vectors.

2024-09-02 12:00 UTC, panquez commented on src/geode/model/helpers/ray_tracing.cpp
> +        geode::detail::SurfaceMeshMerger3D border_merger{ border_to_merge,
Do you really need to merge surfaces to count number of intersections?

2024-09-02 17:12 UTC, BotellaA commented on src/geode/model/helpers/ray_tracing.cpp
> +    static std::array< geode::Vector3D, 12 > directions = { { geode::Vector3D{
Je confirme, c'est important, idéalement il faudrait pouvoir le mettre constexpr mais je ne sais pas si c'est possible

2024-09-03 07:17 UTC, panquez requested changes

2024-09-09 07:49 UTC, merged

2024-09-09 07:52 UTC, BotellaA commented
:tada: This PR is included in version 15.4.0-rc.1 :tada:

The release is available on [GitHub release](https://github.com/Geode-solutions/OpenGeode/releases/tag/v15.4.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-09-10 00:15 UTC, BotellaA commented
:tada: This PR is included in version 15.4.0 :tada:

The release is available on [GitHub release](https://github.com/Geode-solutions/OpenGeode/releases/tag/v15.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: