fix(AttributeManager): Added a method to import attributes from anoth…
Geode-solutions/OpenGeode pull request #476
Opened 2022-06-16 13:03 UTC by MelchiorSchuh

…er AttributeManager and an index mapping.

2022-06-16 13:07 UTC, panquez approved these changes

2022-06-16 13:07 UTC, panquez commented on tests/basic/test-attribute.cpp
> +    test_number_of_attributes( manager3, 8 );
Could you test all some values ?

2022-06-16 13:07 UTC, panquez commented on include/geode/basic/attribute.h
> +                    attribute->values_[new_index] = values_.at( i );
Maybe it is better to use .value(x) and .set_value(x, T) ?

2022-06-16 14:46 UTC, BotellaA requested changes

2022-06-16 14:46 UTC, BotellaA commented on include/geode/basic/attribute.h
> +            attribute->values_ = values_;
```suggestion
```

2022-06-17 05:16 UTC, BotellaA approved these changes

2022-06-17 08:15 UTC, merged

2022-06-17 08:35 UTC, BotellaA commented
:tada: This PR is included in version 10.5.4 :tada:

The release is available on [GitHub release](https://github.com/Geode-solutions/OpenGeode/releases/tag/v10.5.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: