Feat/model extrusion
Geode-solutions/OpenGeode pull request #679
Opened 2023-03-13 09:27 UTC by francoisbonneau

2023-03-14 11:22 UTC, BotellaA requested changes

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +            : section_{ section },
const & cannot be initialized using { }, this is a bug in old gcc

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +                std::get< 0 >( slice1_conversion_output ) );
It looks like this is part of the process, why is it in the constructor?

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +        ~SectionExtruder() = default;
```suggestion
```

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +                                 .in2out( section_component ) ) );
```suggestion
            return 
                slice0_brep_mapping_.at( brep_component_type )
                    .in2out( section_slice0_mapping_.at( brep_component_type )
                                 .in2out( section_component ) );
```
This is not needed and verbose

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +                                 .in2out( section_component ) ) );
Replace for all the file

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +        geode::uuid extrude_corner( const geode::Corner2D& section_corner )
```suggestion

        geode::uuid extrude_corner( const geode::Corner2D& section_corner )
```
Add spacing before and after a method

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +                geode::OpenGeodePolygonalSurface< 3 >::impl_name_static() ) );
```suggestion
                 ) );
```
Default is polygonal.

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +            auto prev_min_pt =
```suggestion
            const auto prev_min_pt =
```

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +            auto prev_max_pt =
```suggestion
            const auto prev_max_pt =
```

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +            for( const auto v : geode::Range( line_slice0.mesh().nb_edges() ) )
```suggestion
            for( const auto v : geode::Range{ line_slice0.mesh().nb_edges() } )
```

2023-03-14 11:22 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +                    line_slice0.mesh().point( v + 1 ) );
This is not always true. Vertices in an EdgedCurve are not ordered.

2023-03-14 13:35 UTC, panquez approved these changes

2023-03-14 13:35 UTC, panquez commented on bindings/python/tests/model/test-py-convert-brep.py
> +        raise ValueError("[Test] extruded BRep have wrong number of blocks")
```suggestion
    if brep.nb_corners() != 2*section.nb_corners():
        raise ValueError("[Test] Extruded BRep have wrong number of corners")
    if brep.nb_lines() != 2*section.nb_lines()+section.nb_corners():
        raise ValueError("[Test] Extruded BRep have wrong number of lines")
    if brep.nb_surfaces() != 2*section.nb_surfaces()+section.nb_lines():
        raise ValueError("[Test] Extruded BRep have wrong number of surfaces")
    if brep.nb_blocks() != section.nb_surfaces():
        raise ValueError("[Test] Extruded BRep have wrong number of blocks")
```

2023-03-14 13:35 UTC, panquez commented on src/geode/model/helpers/convert_brep_section.cpp
> +            geode::BRepConcatener brep_concatener( brep_ );
```suggestion
            geode::BRepConcatener brep_concatener{ brep_ };
```

2023-03-14 13:35 UTC, panquez commented on src/geode/model/helpers/convert_brep_section.cpp
> +        geode::uuid extrude_corner( const geode::Corner2D& section_corner )
You do not use the returned uuid. Is it intentional?

2023-03-14 13:35 UTC, panquez commented on src/geode/model/helpers/convert_brep_section.cpp
> +        OPENGEODE_ASSERT( min_coordinate < max_coordinate,
ASSERT or EXCEPTION? Is it really needed?

2023-03-14 19:20 UTC, BotellaA approved these changes

2023-03-14 19:20 UTC, BotellaA commented on src/geode/model/helpers/convert_brep_section.cpp
> +            for( const auto v : geode::Range{ line_slice0.mesh().nb_edges() } )
Maybe v is not a good iterator name since it is more edge than vertex related

2023-03-15 10:42 UTC, merged

2023-03-15 11:06 UTC, BotellaA commented
:tada: This PR is included in version 13.2.0 :tada:

The release is available on [GitHub release](https://github.com/Geode-solutions/OpenGeode/releases/tag/v13.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: